export const REQUEST_COMBO_POLICY = 'REQUEST_COMBO_POLICY'
export const STOP_REQUEST_COMBO_POLICY = 'STOP_REQUEST_COMBO_POLICY'
export const RECEIVE_FULL_COMBO_POLICY = 'RECEIVE_FULL_COMBO_POLICY'
export const RECEIVE_EXTRA_COMBO_POLICY = 'RECEIVE_EXTRA_COMBO_POLICY'

export const ADD_COMBO_POLICY = 'ADD_COMBO_POLICY'
export const DELETE_COMBO_POLICY = 'DELETE_COMBO_POLICY'
export const EDIT_COMBO_POLICY = 'EDIT_COMBO_POLICY'
