
export const REQUEST_VOUCHER = 'REQUEST_VOUCHER'
export const STOP_VOUCHER_REQUEST = 'STOP_VOUCHER_REQUEST'
export const RECEIVE_VOUCHER = 'RECEIVE_VOUCHER'
export const RECEIVE_EXTRA_VOUCHER = 'RECEIVE_EXTRA_VOUCHER'
export const RECEIVE_DETAIL_VOUCHER = 'RECEIVE_DETAIL_VOUCHER'
export const RECEIVE_GIFT_VOUCHERS = 'RECEIVE_GIFT_VOUCHERS'



