export const SEND_REQUEST_LOGIN = 'SEND_REQUEST_LOGIN'
export const STOP_REQUEST_LOGIN = 'SEND_REQUEST_LOGIN'
export const AUTHENTICATION_SUCCEEDED = 'AUTHENTICATION_SUCCEEDED'
export const LOGOUT = 'LOGOUT'
