export const SEND_COMPAIGN_REQUEST = 'SEND_COMPAIGN_REQUEST' 
export const STOP_COMPAIGN_REQUEST = 'STOP_COMPAIGN_REQUEST' 
export const RECEIVE_FULL_COMPAIGN = 'RECEIVE_FULL_COMPAIGN' 
export const RECEIVE_COMPAIGN_DETAIL = 'RECEIVE_COMPAIGN_DETAIL' 

export const ADD_COMPAIGN = 'ADD_COMPAIGN' 
export const EDIT_COMPAIGN = 'EDIT_COMPAIGN' 
export const DELETE_COMPAIGN = 'DELETE_COMPAIGN' 

