
export const REQUEST_COMBOS = 'REQUEST_COMBOS'
export const STOP_COMBOS_REQUEST = 'STOP_COMBOS_REQUEST'
export const RECEIVE_COMBOS = 'RECEIVE_COMBOS'
export const RECEIVE_EXTRA_COMBOS = 'RECEIVE_EXTRA_COMBOS'
export const RECEIVE_DETAIL_COMBO = 'RECEIVE_DETAIL_COMBO'
export const EDIT_COMBO = 'EDIT_COMBO'
export const DELETE_COMBO = 'DELETE_COMBO'
export const ADD_COMBO = 'ADD_COMBO'



